### ISSUE TITLE
Use real dependency/constructor injection inside eventric

### ISSUE THREAD

**Issue by alexlawrence** [efacilitation/eventric#13]
The recent change replaced autonomous component require() calls with constructor injection of a single registry for all eventric components (used as _eventric locally). 

Altough this goes into the right direction of constructor injection using one global component registry it is less understandable and more tedious in test setup than real dependency injection of individual components.

Take the Repository constructor for example:

```coffeescript
class Repository
  constructor: (params, @_eventric) ->
    @_aggregateName = params.aggregateName
    @_AggregateRoot = params.AggregateRoot
    @_context = params.context
    @_eventric = params.eventric
    @_command = {}  
    @_aggregateInstances = {}
    @_store = @_context.getDomainEventsStore()
```

Looking at the constructor there is no way to know that `Repository` has a dependency to `Aggregate`. With real constructor injection this would be:

```coffeescript
class Repository
  constructor: (params, @$Aggregate) ->
    @_aggregateName = params.aggregateName
    @_AggregateRoot = params.AggregateRoot
    @_context = params.context
    @_eventric = params.eventric
    @_command = {}  
    @_aggregateInstances = {}
    @_store = @_context.getDomainEventsStore()
```

This way dependencies are far more explicit.

We should consider using an IOC/DI container like http://www.royjacobs.org/intravenous/

**Comment by Sandreu** [comment]
``` coffee
Aggregate = require '../Aggregate'

class Repository
  constructor: (params) ->
    #...
```
Why this syntax isn't used ?

**Comment by alexlawrence** [comment]
Because in my opinion this would be service location and not dependency injection. Service location is when modules/units actively request a service from a service registry. Although you could modify how require() resolves modules and also fake it in the specs and then argue that is a kind of dependency injection I think it is not.

The advantage of dependency injection over service location is that your modules do not have to know where and how to get their dependencies. They get their dependencies injected. In your example Repository has to know where Aggregate is to find, in a dependency injected it does not. Only the bootstrapping code has to know this.

**Comment by Sandreu** [comment]
Well, I got your point. :) 
In my projects I use the index of folders to get the service (so no extension) in node and use browserify to expose them as require('project_name/service')

I agree this can be ambiguous.
Regards.

**Comment by alexlawrence** [comment]
Closing for now (see #33). Will come up again if required.
