### ISSUE TITLE
Replace DomainEvent "Function-Definition" with "Array-Definition"

### ISSUE THREAD

**Issue by ghost** [efacilitation/eventric#17]
Currently we define DomainEvents like that

```javascript
context.defineDomainEvent('SomethingHappened', function(params) {
  this.foo = params.foo
});
```

This is really verbose and has no real value.

Instead we want to define DomainEvents like that

```javascript
context.defineDomainEvent('SomethingHappened', ['foo']);
```

This is way less verbose and will have a value since we

- make parameter presence-checks when the DomainEvent gets created.
- warn if parameters are given which are not defined in the array

[Outcome of the issue #14]

**Comment by alexlawrence** [comment]
Closing for now (see #33). Will come up again if required.
