### ISSUE TITLE
Website not rendering

### ISSUE THREAD

**Issue by neverfox** [efacilitation/eventric#25]
![screenshot from 2015-02-06 21 42 10](https://cloud.githubusercontent.com/assets/3344033/6090477/22712230-ae49-11e4-90d1-d932df720b58.png)

**Comment by alexlawrence** [comment]
Thanks for the information. We are aware of this issue. The current website is a work in progress and based on the project https://github.com/efacilitation/eventric-app
However it does render (http://eventricjs.org/#!/api/), it´s just not complete yet.
