### ISSUE TITLE
Cant initialize remote store

### ISSUE THREAD

**Issue by chilicoder** [efacilitation/eventric#39]
i tryed to make work todoMVC example with `remoteStore = true` option and failed.

In `context.coffee`  
[link(https://github.com/efacilitation/eventric/blob/6376da67e1825e343d7e94ade83164f7a0f21a86/src/context/context.coffee#L139) we have two arguments provided to the `.initialize()` function. This works for `inmemory` store well.

But in remoteStore [link] (https://www.npmjs.com/package/eventric-store-remote) we have `initialize(contextName, options, callback)` with code
```javascript
 _contextName = arguments[0], _arg = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callback = arguments[_i++];
    this._contextName = _contextName;
```

This results errors due to lack of the callback

**Comment by alexlawrence** [comment]
Neither the eventric TodoMVC example nor the following repositories are supported anymore:
* https://www.npmjs.com/package/eventric-store-remote
* https://www.npmjs.com/package/eventric-store-lowdb
* https://www.npmjs.com/package/eventric-store-tingodb

We forgot to delete the npm packages. Sorry.

**Comment by chilicoder** [comment]
But how should I instantiate `eventric-remote-socketio-client` then?
```javascript
eventricRemoteSocketIoClient = require 'eventric-remote-socketio-client'
eventricRemoteSocketIoClient.initialize(????).then(????)
```

**Comment by alexlawrence** [comment]
This should work, given socket.io-client is included:
```javascript
var socket = io('http://localhost');
eventricRemoteSocketIoClient = require 'eventric-remote-socketio-client'
eventricRemoteSocketIoClient.initialize({ioClientInstance: socket})
```

https://github.com/efacilitation/eventric-remote-socketio-client/blob/master/src/client.spec.coffee#L65

**Comment by chilicoder** [comment]
Ok, i managed to connect. 

Thanks for help. I will proceed next days, maybe i could manage to make working example. Now i have error
```
Tried to handle Remote RPC with not registered context todomvc
```

but didn't investigate why

**Comment by chilicoder** [comment]
Next station is creation of serverside context
```coffeescript
  eventricSocketIORemoteEndpoint = require 'eventric-remote-socketio-endpoint'
  EventricStoreMongoDb           = require 'eventric-store-mongodb'
  console.log 'eventricSocketIORemoteEndpoint initing'
  eventricSocketIORemoteEndpoint.initialize {}, ->
    eventric.addRemoteEndpoint 'socketio', eventricSocketIORemoteEndpoint
    console.log('todomvc loading')
    todomvc =   eventric.context('todomvc')
    console.log('todomvc loaded')
    resolve todomvc

```

in console i've got 
`todomvc loading` but not `todomvc loaded`

**Comment by chilicoder** [comment]
well.. looks like the problem was in Promise, that is required but loaded nowhere
`global.Promise = require('promise');`

fixes the promlem

**Comment by chilicoder** [comment]
Next station)

I've got request in `endpoint.js` from SocketIOClient
```javascript
rpcRequest  { contextName: 'todomvc',
  functionName: 'command',
  args: [ 'AddTodo', { title: 'asdf' } ],
  rpcId: '383890c6-688b-158e-33c7-af70105eeca8' }
```

but in 

SocketIORemoteEndpoint.prototype._handleRpcRequestEvent in responce function  `console.log(error,response);` returns

`[TypeError: Object #<Object> has no method '$repository'] undefined`

debug log on initialization is
```
[todomvc] Initializing
[todomvc] Initializing Store
[todomvc] Initializing Store inmemory
[todomvc] Initializing Store mongodb
[todomvc] Finished initializing Store inmemory
[todomvc] Finished initializing Store mongodb
[todomvc] Finished initializing Store
[todomvc] Initializing Projections
[todomvc] Initializing Projection Todos
[todomvc] Initializing Projection TodoStats
[todomvc] Clearing ProjectionStores undefined of Todos
[todomvc] Finished clearing ProjectionStores of Todos
[todomvc] No initialize function on Projection Todos given, skipping
[todomvc] Replaying DomainEvents against Projection Todos
[todomvc] Finished Replaying DomainEvents against Projection Todos
[todomvc] Finished initializing Projection Todos
[todomvc] Clearing ProjectionStores undefined of TodoStats
[todomvc] Finished clearing ProjectionStores of TodoStats
[todomvc] No initialize function on Projection TodoStats given, skipping
[todomvc] Replaying DomainEvents against Projection TodoStats
[todomvc] Finished Replaying DomainEvents against Projection TodoStats
[todomvc] Finished initializing Projection TodoStats
[todomvc] Finished initializing Projections
[todomvc] Finished initializing
```

**Comment by alexlawrence** [comment]
Can you provide the code which produces this error?

**Comment by chilicoder** [comment]
Well, I think its better to close it now.
