### ISSUE TITLE
How to use queries?

### ISSUE THREAD

**Issue by chilicoder** [efacilitation/eventric#41]
Hello, 

Is there any example of how to use queries? I did something like this:

```
			context.addQueryHandlers({
				getTodoList: function(params){
					return this;
				}
			});
```

and in this I see some strange object, that doesnt have any information how to retrieve data.

**Comment by alexlawrence** [comment]
Hi,

please have a look at the updated README / tutorial: https://github.com/efacilitation/eventric#query-handlers
