### ISSUE TITLE
Incorrect event delivery when multiple projections are added to a context

### ISSUE THREAD

**Issue by matobet** [efacilitation/eventric#43]
I have followed theTodo example stated in README and I encountered strange behavior that the first projection would appear to receive no events at all and the second one would receive both of them. I then tried adding more projections and it seems that the last projection always gets messages on behalf of all projections and the rest gets nothing.

**Comment by matobet** [comment]
I managed to trace the issue down to insidious capture of loop variable in Context._initializeProjections, submitted PR #44 

Otherwise I have to say, great framework! It seems to be exactly what I've been looking for (except, well I need more than one projection ;-D). Keep up the good work! :+1:

**Comment by mwager** [comment]
Thanks! we are currently working on it. Sorry for the late response
